"""stage 2: render takes + audio asset singer/label

Revision ID: 1fbb3564c02e
Revises: 2a8be582db75
Create Date: 2026-08-31 11:09:28.576171
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1fbb3564c02e'
down_revision: str | None = '2a8be582db75'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('render_takes',
    sa.Column('generation_job_id', sa.String(length=36), nullable=False),
    sa.Column('vocal_role_id', sa.String(length=36), nullable=False),
    sa.Column('singer_id', sa.String(length=36), nullable=False),
    sa.Column('take_index', sa.Integer(), nullable=False),
    sa.Column('child_seed', sa.Integer(), nullable=False),
    sa.Column('timing_offset_ms', sa.Float(), nullable=False),
    sa.Column('pitch_cents', sa.Float(), nullable=False),
    sa.Column('formant_shift', sa.Float(), nullable=False),
    sa.Column('gain_db', sa.Float(), nullable=False),
    sa.Column('pan', sa.Float(), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('source_asset_id', sa.String(length=36), nullable=True),
    sa.Column('output_asset_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_asset_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['singer_id'], ['singers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vocal_role_id'], ['vocal_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('render_takes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_render_takes_generation_job_id'), ['generation_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_takes_singer_id'), ['singer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_takes_vocal_role_id'), ['vocal_role_id'], unique=False)

    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('singer_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('label', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_audio_assets_singer_id'), ['singer_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_audio_assets_singer_id', 'singers', ['singer_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audio_assets_singer_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audio_assets_singer_id'))
        batch_op.drop_column('label')
        batch_op.drop_column('singer_id')

    with op.batch_alter_table('render_takes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_render_takes_vocal_role_id'))
        batch_op.drop_index(batch_op.f('ix_render_takes_singer_id'))
        batch_op.drop_index(batch_op.f('ix_render_takes_generation_job_id'))

    op.drop_table('render_takes')
    # ### end Alembic commands ###
