"""initial schema (through stage 1)

Revision ID: 2a8be582db75
Revises: 
Create Date: 2026-08-31 10:31:49.735857
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2a8be582db75'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bands',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('band_references',
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key', sa.String(length=20), nullable=True),
    sa.Column('tuning', sa.String(length=40), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('structure_json', sa.JSON(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_for_training', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('band_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_band_references_band_id'), ['band_id'], unique=False)

    op.create_table('projects',
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_band_id'), ['band_id'], unique=False)

    op.create_table('singers',
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('voice_model_provider', sa.String(length=60), nullable=True),
    sa.Column('voice_model_path_or_id', sa.String(length=500), nullable=True),
    sa.Column('clean_enabled', sa.Boolean(), nullable=False),
    sa.Column('scream_enabled', sa.Boolean(), nullable=False),
    sa.Column('training_status', sa.String(length=20), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('consent_training', sa.Boolean(), nullable=False),
    sa.Column('consent_generation', sa.Boolean(), nullable=False),
    sa.Column('consent_commercial', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=60), nullable=True),
    sa.Column('consent_source_ref', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('band_id', 'name', name='uq_singer_band_name')
    )
    with op.batch_alter_table('singers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_singers_band_id'), ['band_id'], unique=False)

    op.create_table('songs',
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key', sa.String(length=20), nullable=True),
    sa.Column('time_signature', sa.String(length=12), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('reference_profile_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reference_profile_id'], ['band_references.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songs_band_id'), ['band_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_project_id'), ['project_id'], unique=False)

    op.create_table('song_sections',
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('section_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('prompt_override', sa.Text(), nullable=True),
    sa.Column('generation_seed', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_sections_song_id'), ['song_id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('song_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('provider_version', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('input_asset_ids', sa.JSON(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['song_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_song_id'), ['song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_status'), ['status'], unique=False)

    op.create_table('lyric_lines',
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['song_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lyric_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lyric_lines_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lyric_lines_song_id'), ['song_id'], unique=False)

    op.create_table('audio_assets',
    sa.Column('song_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('generation_job_id', sa.String(length=36), nullable=True),
    sa.Column('parent_asset_id', sa.String(length=36), nullable=True),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['audio_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['song_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_assets_generation_job_id'), ['generation_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_assets_parent_asset_id'), ['parent_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_assets_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_assets_song_id'), ['song_id'], unique=False)

    op.create_table('vocal_roles',
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('lyric_line_id', sa.String(length=36), nullable=True),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('ensemble_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('humanize_timing_ms', sa.Float(), nullable=False),
    sa.Column('humanize_pitch_cents', sa.Float(), nullable=False),
    sa.Column('humanize_formant', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(section_id IS NOT NULL) <> (lyric_line_id IS NOT NULL)', name='ck_vocal_role_exactly_one_parent'),
    sa.ForeignKeyConstraint(['lyric_line_id'], ['lyric_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['song_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocal_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocal_roles_lyric_line_id'), ['lyric_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocal_roles_section_id'), ['section_id'], unique=False)

    op.create_table('vocal_assignments',
    sa.Column('vocal_role_id', sa.String(length=36), nullable=False),
    sa.Column('singer_id', sa.String(length=36), nullable=False),
    sa.Column('weight_percent', sa.Float(), nullable=False),
    sa.Column('gain_db', sa.Float(), nullable=False),
    sa.Column('pan', sa.Float(), nullable=False),
    sa.Column('pitch_offset_semitones', sa.Float(), nullable=False),
    sa.Column('timing_offset_ms', sa.Float(), nullable=False),
    sa.Column('formant_shift', sa.Float(), nullable=False),
    sa.Column('style', sa.String(length=40), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['singer_id'], ['singers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocal_role_id'], ['vocal_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocal_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocal_assignments_singer_id'), ['singer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocal_assignments_vocal_role_id'), ['vocal_role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocal_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocal_assignments_vocal_role_id'))
        batch_op.drop_index(batch_op.f('ix_vocal_assignments_singer_id'))

    op.drop_table('vocal_assignments')
    with op.batch_alter_table('vocal_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocal_roles_section_id'))
        batch_op.drop_index(batch_op.f('ix_vocal_roles_lyric_line_id'))

    op.drop_table('vocal_roles')
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_assets_song_id'))
        batch_op.drop_index(batch_op.f('ix_audio_assets_section_id'))
        batch_op.drop_index(batch_op.f('ix_audio_assets_parent_asset_id'))
        batch_op.drop_index(batch_op.f('ix_audio_assets_generation_job_id'))
        batch_op.drop_index(batch_op.f('ix_audio_assets_asset_type'))

    op.drop_table('audio_assets')
    with op.batch_alter_table('lyric_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lyric_lines_song_id'))
        batch_op.drop_index(batch_op.f('ix_lyric_lines_section_id'))

    op.drop_table('lyric_lines')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_song_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_section_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_job_type'))

    op.drop_table('generation_jobs')
    with op.batch_alter_table('song_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_sections_song_id'))

    op.drop_table('song_sections')
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_project_id'))
        batch_op.drop_index(batch_op.f('ix_songs_band_id'))

    op.drop_table('songs')
    with op.batch_alter_table('singers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_singers_band_id'))

    op.drop_table('singers')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_band_id'))

    op.drop_table('projects')
    with op.batch_alter_table('band_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_band_references_band_id'))

    op.drop_table('band_references')
    op.drop_table('bands')
    # ### end Alembic commands ###
