"""stage 4: intervals, role processing, presets, job result

Revision ID: 4b1259554c73
Revises: 4ba7cbb35398
Create Date: 2026-08-31 13:23:03.251703
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4b1259554c73'
down_revision: str | None = '4ba7cbb35398'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocal_presets',
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('band_id', 'name', name='uq_vocal_preset_band_name')
    )
    with op.batch_alter_table('vocal_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocal_presets_band_id'), ['band_id'], unique=False)

    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('vocal_assignments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('interval_semitones', sa.Float(), nullable=False, server_default='0')
        )

    with op.batch_alter_table('vocal_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocal_roles', schema=None) as batch_op:
        batch_op.drop_column('processing_json')

    with op.batch_alter_table('vocal_assignments', schema=None) as batch_op:
        batch_op.drop_column('interval_semitones')

    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_column('result_json')

    with op.batch_alter_table('vocal_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocal_presets_band_id'))

    op.drop_table('vocal_presets')
    # ### end Alembic commands ###
