"""stage 3: render cache + singer voice profile

Revision ID: 4ba7cbb35398
Revises: 1fbb3564c02e
Create Date: 2026-08-31 12:55:24.356993
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4ba7cbb35398'
down_revision: str | None = '1fbb3564c02e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('render_cache',
    sa.Column('cache_key', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('provider_version', sa.String(length=60), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('render_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_render_cache_cache_key'), ['cache_key'], unique=True)

    with op.batch_alter_table('singers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_profile_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('singers', schema=None) as batch_op:
        batch_op.drop_column('voice_profile_json')

    with op.batch_alter_table('render_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_render_cache_cache_key'))

    op.drop_table('render_cache')
    # ### end Alembic commands ###
