"""stage 7: band adapters

Revision ID: 877aea557911
Revises: 924a5822279e
Create Date: 2026-08-31 14:22:01.212107
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '877aea557911'
down_revision: str | None = '924a5822279e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_adapters',
    sa.Column('band_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('provider_version', sa.String(length=60), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=True),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('band_id', 'name', name='uq_band_adapter_name')
    )
    with op.batch_alter_table('band_adapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_band_adapters_band_id'), ['band_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_adapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_band_adapters_band_id'))

    op.drop_table('band_adapters')
    # ### end Alembic commands ###
