"""stage 6: band reference analysis fields

Revision ID: 924a5822279e
Revises: 4b1259554c73
Create Date: 2026-08-31 14:04:54.228941
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '924a5822279e'
down_revision: str | None = '4b1259554c73'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_kind', sa.String(length=20), nullable=False, server_default='upload'))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sample_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('channels', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quality_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('analysis_status', sa.String(length=20), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('analysis_provider', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('analysis_version', sa.String(length=60), nullable=True))
        batch_op.create_unique_constraint('uq_band_reference_content', ['band_id', 'content_hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_references', schema=None) as batch_op:
        batch_op.drop_constraint('uq_band_reference_content', type_='unique')
        batch_op.drop_column('analysis_version')
        batch_op.drop_column('analysis_provider')
        batch_op.drop_column('analysis_status')
        batch_op.drop_column('quality_json')
        batch_op.drop_column('channels')
        batch_op.drop_column('sample_rate')
        batch_op.drop_column('duration')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('source_kind')

    # ### end Alembic commands ###
